In [40]:
import pandas as pd
import numpy as np
import math
import operator

In [41]:
data = pd.read_csv("iris.csv")
data.head()

,SepalLength,SepalWidth,PetalLength,PetalWidth,Name
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa


In [42]:
def euclideanDistance(data1, data2, length):
    distance = 0
    for x in range(length):
        distance += np.square(data1[x] - data2[x])
    return np.sqrt(distance)

In [43]:
def knn(trainingSet, testInstance, k):
    distances = {}
    sort = {}

    length = testInstance.shape[1]
    
    for x in range(len(trainingSet)):
        dist = euclideanDistance(testInstance, trainingSet.iloc[x], length)
        distances[x] = dist[0]
    sorted_d = sorted(distances.items(), key=operator.itemgetter(1))
    neighbors = []
    
    for x in range(k):
        neighbors.append(sorted_d[x][0])
    classVotes = {}

    for x in range(len(neighbors)):
        response = trainingSet.iloc[neighbors[x]][-1]
        if response in classVotes:
            classVotes[response] += 1
        else:
            classVotes[response] = 1
    sortedVotes = sorted(classVotes.items(), key=operator.itemgetter(1), reverse=True)
    return(sortedVotes[0][0], neighbors)


In [44]:
testSet = [[7.2, 3.6, 5.1, 2.5]]
test = pd.DataFrame(testSet)
k = 1
result,neigh = knn(data, test, k)
print(result)
print(neigh)

Iris-virginica
[141]


/var/folders/59/6tnms26n4qbb84m41ww6y3xw0000gn/T/ipykernel_8545/1999276246.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  distance += np.square(data1[x] - data2[x])
/var/folders/59/6tnms26n4qbb84m41ww6y3xw0000gn/T/ipykernel_8545/2024214515.py:18: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  response = trainingSet.iloc[neighbors[x]][-1]


In [45]:
testSet = [[4.9, 3.0, 1.4, 0.2]]
test = pd.DataFrame(testSet)
k = 1
result,neigh = knn(data, test, k)
print(result)
print(neigh)

Iris-setosa
[1]


/var/folders/59/6tnms26n4qbb84m41ww6y3xw0000gn/T/ipykernel_8545/1999276246.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  distance += np.square(data1[x] - data2[x])
/var/folders/59/6tnms26n4qbb84m41ww6y3xw0000gn/T/ipykernel_8545/2024214515.py:18: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  response = trainingSet.iloc[neighbors[x]][-1]


In [48]:
k = 3
result,neigh = knn(data, test, k) 
print(result) 
print(neigh)

Iris-setosa
[1, 45, 12]


/var/folders/59/6tnms26n4qbb84m41ww6y3xw0000gn/T/ipykernel_8545/1999276246.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  distance += np.square(data1[x] - data2[x])
/var/folders/59/6tnms26n4qbb84m41ww6y3xw0000gn/T/ipykernel_8545/2024214515.py:18: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  response = trainingSet.iloc[neighbors[x]][-1]


In [49]:
k = 5
result,neigh = knn(data, test, k) 
print(result) 
print(neigh)

Iris-setosa
[1, 45, 12, 9, 34]


/var/folders/59/6tnms26n4qbb84m41ww6y3xw0000gn/T/ipykernel_8545/1999276246.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  distance += np.square(data1[x] - data2[x])
/var/folders/59/6tnms26n4qbb84m41ww6y3xw0000gn/T/ipykernel_8545/2024214515.py:18: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  response = trainingSet.iloc[neighbors[x]][-1]


In [66]:
# Comparing our model with scikit-learn
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

In [67]:
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(data.iloc[:,0:4], data['Name'])

print(neigh.predict(test))
#knn.fit(X, y)
y_pred = neigh.predict(data.iloc[:,0:4])
print(metrics.accuracy_score(data['Name'], y_pred))
print(neigh.kneighbors(test)[1])

['Iris-setosa']
0.96
[[ 1 45 12]]


/Users/rajthakur/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
/Users/rajthakur/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [80]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix
x=data[['PetalLength','PetalWidth']]
y=data['Name']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [82]:
k=5
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy:{accuracy}")
print("Confusion Matrix:",confusion_matrix(y_test,y_pred))

Accuracy:1.0
Confusion Matrix: [[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
